allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
minimumReleaseAgeExclude:
  - '@next/*'
  - next
  - icu-minify@4.14.3
  - next-intl-swc-plugin-extractor@4.14.3
  - next-intl@4.14.3
  - use-intl@4.14.3
